/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeSwitcher: typeof import('./src/components/DarkModeSwitcher.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
  }
}
